language: node_js
before_install:
- npm install -g npm@'>=2.13.5'
- chmod +x -R build
script: npm test
before_deploy:
- npm install
after_success:
- "./build/repo-cli.sh"
deploy:
  provider: npm
  email: todd@deepelement.com
  api_key:
    secure: M6AWdklaZfNnA6rN2qffckegnGmrsagJMHMYvFhwMTpqavTknuvONVDNPqdPvw3PYihwr3V9wkXOTBwWzLIPSYJTNHAy2Oa3MWTN/lnQ9SM8f9I2smQMoLZGt0BmZkM4hSzbIggp84XppvYcvxLaG0FS/7ZGF5pbd28xWkU9Bi2yJDzTbyQLimwRURXhZpQwnQN02sktEn281skkhk/vDgzXPdHCy2vw9gGm1v6grA8EmKOLwMvii0/2WeS+nvj1Djkjxl3E7PAVLCSmmvbm1UayxSwuLbKWqP2oYqx3tfvlNyhR+yGTxcIEZ9+IBB9KINjPK2CzcAkdzelxALnrCvIhLf1sCSulUbeUluLnR5lrEg3DbItRotIpJqs8UmxZT731uEEbQjKRSK5uWKH+iyhYgShxUxsQHI8uHp7RG2wSq4oiElArI85wbc0SOCronD06wQJkq4hSLUqGO8zBu0VhojQ5xiA8t34G8fmg+HgiNwqvZFXzOs3bF0iNpwkrCfCGjBFLHGXTC4slas5kjYod9CGnv2rRVwi2rkbOZ5CqW5XUCgd840TOF5e7kQw4/T4ecu0yumGqIMoNltb7olCP0ee1v3cyetzxvu6kFnmD6PIkDcOhx7igHth6J+Akp7Zt7+d4dXVTiEHmg8ojZf37RRvGJACtXSA3UYzE1iw=
  on:
    repo: DeepElement/winjs-rocks
