language: node_js
script: npm test
after_success:
- if [ $TRAVIS_BRANCH != "master" ]; exit 1; fi
- git config --global user.email "${GIT_EMAIL}"
- git config --global user.name "${GIT_NAME}"
- git clone --quiet --branch=stable https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
  travis-build > /dev/null
- cd travis-build
- git fetch --quiet > /dev/null
- git merge origin/master --no-commit > /dev/null
- git commit -m "Travis CI auto-merge from travis build ${TRAVIS_BUILD_NUMBER}"
- npm version patch -m "Travis CI auto-version from travis build ${TRAVIS_BUILD_NUMBER}"
- git push -fq origin stable > /dev/null
before_deploy:
- npm install
deploy:
  skip_cleanup: true
  provider: npm
  email: todd@deepelement.com
  api_key:
    secure: jKEPZCrwPZl+ki1/gY1t0XIHdT6kkAmZDBog7WcuwZiYfPk4+ZZ1mhe98QXSFxz8uSgWhI/7pKDRzi/Qu8qY95LLMsxc+g6gkuwxcErP25OQT7wqTLPi0uJVKGuOg4W6CLN9g0z+QnxstFEOJpcpeJwBnpXxl8fkqr8qNhUV4WzV+tX366cnvc1t78HRX1TloA2+BAoBJOzy8Po+MykASHcR2dLs6WtHSpT6m72YbyGQQSd2mAOVgIHR5o2odwkeC8JFXgNHnh3IJpCvWfaVNRYBqciXQY2ZIgyicPU3p21o2qr59epQSehdtHqTxX7FuNSQEkQ0ln9U4Ubc1F9Dy22wuEAnH7isMMffMSfIIGYGUzIs+UbD1cPS/MUhdV7U8ULqtodBzQZoMvGpd41Pm1LcYVEgMzAaPPYlCorZ0dCN8FgfEzFOdIRScmZf6gkI2HvopQ6wFpi33ZEqAvavE6ych7lPFPmpFjVTzS4wFY75gDFXwTGESUksD7ef4lRRpwRgkfK66vjcJfs6Wy8mP4jodyWRTF51o8SdPsZt6dWWa1qJfOHxsmPpHp/1CPttLj3sL9odAJqOJBnsqdP1S5uISqlFua24qX43+K6rcB8+l16uFT+5WHiSRsgqqGnOEnInFRx0te6z+suz/w0TkYNRNpwzj3Kq/m7SRf62fB8=
  on:
    repo: DeepElement/winjs-rocks
    branch: stable
