language: node_js
before_install:
- npm install -g npm@'>=2.13.5'
- chmod +x -R build
script: npm test
before_deploy:
- npm install
after_success:
- "./build/repo-cli.sh"
deploy:
  skip_cleanup: true
  provider: npm
  email: todd@deepelement.com
  api_key:
    secure: G/71aydKtPgPW9QS/m+CeVxhCpGT70tyxDOcFFJekEirH94Szm7Yw98PvHOJCBGnaQumVWfYfg0X67Ch1NGvEIp+KQgJ62RHufw0gpjWAOMCFmW1erxg+Odd3wyfIEHc9v1RL56Chdk9RweguaCgebikusYxaWSzqvRrvYC5jYHQevnbisoefl5hPWugHNvlsXQtnJIhOEvI16/ZL4X78y0WRbYiu9TxSFQH+Az4uZz0aQdpVAN6piIZRQ7sJrO3qCV7tXFtZSt+vpzBKvvuDD63xIPNwrBQwFSlARd7YsjGeO6En3OnAh5Urckc2+yUcThJEC+i38xxxcmIfszFj1I/8XsNMuVFF1bvAP1d8FXWYcfQ5SH8c6upiRyGSDpCoSJZbFpysi1v8qHihvKGS5bqvwnmM7X77KIQc8kU08tO1xWYJ51LIv13hV7XECBeHQxpmFzuZdNI3BNJKNaC9YT5b09ftkS58EbQyzO3Q2ASxYWXbd7B3WWE7lLYTPp7pppNcsobaVkQbfBzWpOjWQCWFAyta46qf9EVAtwFul2HF2w1RuPGg9A3TIN5Wxp2jmK/KkuxQYucu6tp0qawVkAdxoxvrBXrenQaPmLEt5oCgimMBODJd1mdomUtd/W2gGupwbTbnsQ+uTFf+OgTFladzJmLWpS+6M+Ny3uergc=
  on:
    repo: DeepElement/winjs-rocks
    branch: stable
