language: node_js
before_install:
  - npm install -g npm@'>=2.13.5'
  - chmod +x -R build
script: npm test
before_deploy:
- npm install
after_success:
- "./build/repo-cli.sh"
deploy:
  skip_cleanup: true
  provider: npm
  email: todd@deepelement.com
  api_key:
    secure: jKEPZCrwPZl+ki1/gY1t0XIHdT6kkAmZDBog7WcuwZiYfPk4+ZZ1mhe98QXSFxz8uSgWhI/7pKDRzi/Qu8qY95LLMsxc+g6gkuwxcErP25OQT7wqTLPi0uJVKGuOg4W6CLN9g0z+QnxstFEOJpcpeJwBnpXxl8fkqr8qNhUV4WzV+tX366cnvc1t78HRX1TloA2+BAoBJOzy8Po+MykASHcR2dLs6WtHSpT6m72YbyGQQSd2mAOVgIHR5o2odwkeC8JFXgNHnh3IJpCvWfaVNRYBqciXQY2ZIgyicPU3p21o2qr59epQSehdtHqTxX7FuNSQEkQ0ln9U4Ubc1F9Dy22wuEAnH7isMMffMSfIIGYGUzIs+UbD1cPS/MUhdV7U8ULqtodBzQZoMvGpd41Pm1LcYVEgMzAaPPYlCorZ0dCN8FgfEzFOdIRScmZf6gkI2HvopQ6wFpi33ZEqAvavE6ych7lPFPmpFjVTzS4wFY75gDFXwTGESUksD7ef4lRRpwRgkfK66vjcJfs6Wy8mP4jodyWRTF51o8SdPsZt6dWWa1qJfOHxsmPpHp/1CPttLj3sL9odAJqOJBnsqdP1S5uISqlFua24qX43+K6rcB8+l16uFT+5WHiSRsgqqGnOEnInFRx0te6z+suz/w0TkYNRNpwzj3Kq/m7SRf62fB8=
  on:
    repo: DeepElement/winjs-rocks
    branch: stable
