language: node_js
node_js:
- 0.10.33
script: npm test
after_success:
- if [ $TRAVIS_BRANCH != "master" ]; exit 1; fi
- git config --global user.email "${GIT_EMAIL}"
- git config --global user.name "${GIT_NAME}"
- git clone --quiet --branch=stable https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
      travis-build > /dev/null
- cd travis-build
- git fetch --quiet > /dev/null
- git merge origin/master --no-commit > /dev/null
- git commit -m "Travis CI auto-merge from travis build ${TRAVIS_BUILD_NUMBER}"
- npm version patch -m "Travis CI auto-version from travis build ${TRAVIS_BUILD_NUMBER}"
- git push -fq origin stable > /dev/null
before_deploy:
- npm install
deploy:
  skip_cleanup: true
  provider: npm
  email: todd@deepelement.com
  api_key:
    secure: OqVXUM0OFMtBsSKN+CleqK8FK/6VVL16D0M8xeMEN7MN4F6OgxCQ4y9hZehdSxs18tpuVu0JiEkRJuNpTXw25SLuArPXRcPEAKmFxd1yH3DaAg38+JNyneFMEcJbcsc2Ke+wbXGtIwuaKZ+2pUJwSzuuURfT8p5PtkoIUrtKSfHVWpzosS12eaghnwaCRVBT509oNINSO0DNoM9/uxkN9XyPYB0PIBBejGy43aXOfz5kSs0wKonQnD3DvDeVrWKJUcSl0S+DvgjJzp5uNuOh9Xtzf7ACo6AyBaTRJyA7mwMuod+BTZzM5CFHZlYFYlG4B+QSFMm8AtXNRURhdo1qjjSeUM8wdAtYfAaIUXvSDjCMTlhnNYm+ZodUe/0b38bH3IhizcxDMFdxPe8G5FYzbAqTdNk8uOfFYG1HOpOWQy9fHp9FP0r+u7UWczbcnQ+ClmdagMR7qh9yUbZwNAuB9nsrTjy6GCvC81bb28mzzQ2pGi9DFj53wIB0YPzxe8v7AxZMi0ErngKSwuEExFGYJZECr3yge1lES0WbIiecplR2lwpk69IlX6TQdXRnhHkn44BqWXSJyp3YtlzuylyLbnKnrK/sidIrrfiEjKDLOxrogBpVMI3Ark830IwwoNqkXnUD20yaQSVV3TCH1XqfDwEWmcXh+L4dPGaWlmcsS0E=
  on:
    repo: DeepElement/winjs-rocks
    branch: stable
